version: "2.4"

services:
  b2btranslations:
    image: https://hub.docker.com/repository/docker/igoradm90/nest-skeleton
    container_name: nest-skeleton
    environment:
      TZ: Europe/Moscow
    ports:
      - 3001:3000
    volumes:
      - /etc/apps/app/local.json:/opt/docker/config/local.json:ro
      - /var/log/docker/app:/opt/docker/logs
    restart: always
