version: "2.4"

services:
  b2btranslations:
    image: hub.devuptolike.com:5000/b2b/b2btranslations:${CI_COMMIT_SHORT_SHA}
    container_name: account-backend
    environment:
      TZ: Europe/Moscow
    ports:
      - 3001:3000
    volumes:
      - /etc/apps/account/local.json:/opt/docker/config/local.json:ro
      - /var/log/docker/account:/opt/docker/logs
    restart: always
